apps_portfolio/portfolio/urls.py
from django.urls import path
from .views import renderHome, renderProject, renderTest

app_name = 'projects'

urlpatterns = [
    path('', renderHome, name='home'),
    path('projects/<int:Id>', renderProject, name='project'),
    path('test', renderTest, name='test')
]

dj_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps_portfolio.portfolio.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_portfolio/portfolio/models.py
from decimal import Decimal
from django.db import models
from django.utils.timezone import now
from django.core.validators import MinValueValidator, MaxValueValidator

## SKILLS
#  HARD SKILLS
class Hard_Skill (models.Model):
    PL = 'PL' # Programming Language
    DL = 'DL' # Non-programming developing language
    FL = 'FL' # Framework or Library
    DB = 'DB' # Database
    HL = 'HL' # Human Speaking/Writing language
    OS = 'OS' # Operating System
    VT = 'VT' # Virtualization technology
    SW = 'SW' # Software skill
    OT = 'OT' # Other hard skill
    type_skill_choices = [
        (PL, 'Programming Language'),
        (DL, 'Non-programming developing language'),
        (FL, 'Framework or Library'),
        (DB, 'Database'),
        (HL, 'Human Speaking/Writing language'),
        (OS, 'Operating System'),
        (VT, 'Virtualization technology'),
        (SW, 'Software Skill'),
        (OT, 'Other hard skill')
    ]
    type_skill = models.CharField(
        max_length=2,
        choices=type_skill_choices,
        default=PL
    )
    name = models.CharField(max_length=50, verbose_name='Name', blank=False, null=False)
    percentage = models.IntegerField(verbose_name='Percentage', default=0, validators=[MinValueValidator(0), MaxValueValidator(100)], blank=False, null=False)

    def __str__ (self):
        return "[{0}] {1}".format(self.id, self.name)

    class Meta:
        verbose_name = 'Hard Skill'
        verbose_name_plural = 'Hard Skills'

#  SOFT SKILLS
class Soft_Skill (models.Model):
    name = models.CharField(max_length=50, verbose_name='Name', blank=False, null=False)

    def __str__ (self):
        return "[{0}] {1}".format(self.id, self.name)

    class Meta:
        verbose_name = 'Soft Skill'
        verbose_name_plural = 'Soft Skills'

## CREDENTIALS
#  CREDENTIAL EMITTERS
class Credential_Emitter (models.Model):
    name = models.CharField(max_length=50, verbose_name='Name')
    picture = models.ImageField(upload_to='portfolio/pictures/', verbose_name='Picture', null=True)
    url = models.URLField(verbose_name='URL', blank=True, null=True)

    def __str__ (self):
        return "[{0}] {1}".format(self.id, self.name)

    class Meta:
        verbose_name = 'Credential Emitter'
        verbose_name_plural = 'Credential Emitters'

#  CREDENTIALS
class Credential (models.Model):
    name = models.CharField(verbose_name='Name', max_length=50)
    date_earned = models.DateField(verbose_name='Date earned', default=now)
    date_expiration = models.DateField(verbose_name='Date of expiration', blank=True, null=True)
    description = models.TextField(verbose_name='Description', default="", blank=True, null=True)
    embed = models.TextField(verbose_name='Embed Code', default="", blank=True, null=True)
    url = models.URLField(verbose_name='URL', blank=True, null=True)
    document = models.FileField(upload_to='portfolio/documents/', verbose_name='Document', null=True)
    picture = models.ImageField(upload_to='portfolio/pictures/', verbose_name='Picture', null=True)
    hard_skills = models.ManyToManyField(Hard_Skill)
    emitter_credential = models.ManyToManyField(Credential_Emitter)

    P = 'P' # Professional Universitty Title
    T = 'T' # Technician Title
    C = 'C' # Professional Certification
    B = 'B' # Badge
    L = 'L' # Human Language Official Test Certification
    type_credential_choices = [
        (P, 'Professional University Title'),
        (T, 'Technician Title'),
        (C, 'Professional certification'),
        (B, 'Badge'),
        (L, 'Human Language Official Test Certification')
    ]
    type_credential = models.CharField(
        max_length=1,
        choices=type_credential_choices,
        default=B
    )

    def __str__ (self):
        return "[{0}] {1}".format(self.id, self.name)

    class Meta:
        verbose_name = 'Credential'
        verbose_name_plural = 'Credentials'

## PROJECTS
class Project (models.Model):
    name = models.CharField(max_length=50, verbose_name='Name', blank=False, null=False)
    publication_date = models.DateField(verbose_name='Publication Date', default=now)
    start_date = models.DateField(verbose_name='Project Start Date', blank=True, null=True)
    end_date = models.DateField(verbose_name='Project End Date', blank=True, null=True)
    short_description = models.CharField(max_length=100, verbose_name='Short Description', default="", blank=True, null=True)
    long_description = models.TextField(verbose_name='Long Description', default="", blank=True, null=True)
    project_url = models.URLField(verbose_name='Project URL', blank=True, null=True)
    code_url = models.URLField(verbose_name='Code URL', blank=True, null=True)
    picture = models.ImageField(upload_to='portfolio/pictures/', verbose_name='Picture', null=True)
    hard_skills = models.ManyToManyField(Hard_Skill)
    soft_skills = models.ManyToManyField(Soft_Skill)

    def __str__ (self):
        return "[{0}] {1}".format(self.id, self.name)

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'
        ordering = ['-publication_date']

apps_portfolio/portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project, Credential, Hard_Skill, Soft_Skill

def renderHome(request):
    projects = Project.objects.all()
    credentials = Credential.objects.all()
    hard_skills = Hard_Skill.objects.all()
    soft_skills = Soft_Skill.objects.all()
    return render(request, 'home.html', {
        'projects': projects,
        'credentials': credentials,
        'hard_skills': hard_skills,
        'soft_skills': soft_skills
    })

def renderProject(request, Id):
    project = get_object_or_404(Project, pk=Id)
    projects = Project.objects.all()
    return render(request, 'project.html', {
        'actual_project': project,
        'projects': projects
    })

def renderTest(request):
    return render(request, 'test.html')

apps_portfolio/portfolio/templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Welcome to my portfolio!{% endblock title %}

{% block styles %}
    <link href="{% static 'css/home.css' %}" rel="stylesheet" type="text/css">
{% endblock styles %}

{% block content %}
    {% include 'partials/header.html' %}
    <main id="main-container" class="container-fluid">
	    <div class="row">
            {% if credentials|length > 0 or hard_skills|length > 0 or soft_skills|length > 0 %}
	        <div id="lateral-bar" class="col-md-3">
                {% if hard_skills|length > 0 %}
                <h3 class="text-dark">Hard Skills</h3>
                    {% for hs in hard_skills %}
                    {{hs.name}}
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: {{hs.percentage}}%" aria-valuenow="{{hs.percentage}}" aria-valuemin="0" aria-valuemax="100">
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            {% endif %}
	        <div class="col-md-9">
				<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mattis lorem eu tristique molestie. Fusce ultrices leo id ultricies vehicula. Sed non maximus ex. Proin rhoncus placerat vulputate. Vivamus sit amet lorem ante. Nullam fermentum libero ut metus vulputate, ut dignissim metus tempor. Donec posuere lorem lectus, ac vestibulum arcu lobortis ut. Cras non lobortis metus, at hendrerit odio. Proin vulputate vel enim et sollicitudin.
				</p>
                
                {% if projects|length > 0 %}
    
                <div id="projectList" class="row my-4 text-center">

                    <h3>My projects</h3>

                    {% for project in projects %}
                    <a href="{% url 'projects:project' project.id %}">
                    <div class="col-md p-4">
                        <div class="card bg-title card-project">
                            <div class="project-pic-viewport">
                                <img class="project-picture" src="{{project.picture.url}}" alt="">
                            </div>
                            <div class="card-body">
                                <h2>{{project.name}}</h2>
                                <p>{{project.short_description}}</p>

                                {% if project.project_url %}
                                    <a href="{{project.project_url}}"><i class="bi bi-globe2"></i></a>
                                {% endif %}
                                {% if project.code_url %}
                                    <a href="{{project.code_url}}"><i class="bi bi-git"></i></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    </a>
                    {% endfor %}

                </div>

                {% endif %}
    
	        </div>
	    </div>
	</main>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/home.js' %}" type="text/javascript"></script>
{% endblock scripts %}

apps_portfolio/portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    {% block styles %}
    {% endblock styles %}
</head>
<body>
    
    {% include 'partials/navbar.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'partials/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

apps_portfolio/portfolio/templates/project.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}{{actual_project.name}}{% endblock title %}

{% block styles %}
    <link href="{% static 'css/project.css' %}" rel="stylesheet" type="text/css">
{% endblock styles %}

{% block content %}
<header id="item-header" class="container-fluid d-flex align-items-center justify-content-center">
    <div class="row">
        <div class="col-md-8 my-auto text-light p-5">
            <h1 id="title">{{actual_project.name}}</h1>
            <span id="date">{{actual_project.publication_date}}</span>        
        </div>
    </div>
</header>
<main id="main-container" class="container-fluid">
    <div class="row">
        <div id="lateral-bar" class="col-md-3 text-light">
            {% for project in projects %}
            <a href="{% url 'projects:project' project.id %}">
                <p>{{project.name}}</p>
            </a>
            {% endfor %}
        </div>
        <div id="project" class="col-md-9">
            {{actual_project.long_description|safe}}
        </div>
    </div>
</main>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/project.js' %}" type="text/javascript"></script>
{% endblock scripts %}

apps_portfolio/portfolio/templates/test.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Sitio de prueba">
        <meta name="keywords" content="HTML, CSS, JavaScript">
        <meta name="author" content="Roger">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sitio de pruebas</title>
<style>
.viewport {
  width: 300px;
  height: 300px;
  border: 5px solid #4838DE;
  margin: 0;
  overflow: hidden;
  position: relative;
}

.item-pic {
    position: relative;
    top: 0px;
    left: 0px;
}

</style>
    </head>
    <body>
        <div class="viewport">
            <img class="item-pic"
            src="public/portfolio/pictures/2021-08-17-104113_1366x768_scrot.png"
            alt="" />
        </div><br />
        <div class="viewport">
            <img class="item-pic"
            src="static/img/index.jpg"
            alt="" />
        </div><br />
        <img id="mierda"
        src="static/img/index.jpg"
        alt="" />
        <script>
            window.addEventListener('load', (e) => {
                var vp = document.getElementsByClassName("viewport");
                var pic = document.getElementsByClassName("item-pic");
                for (let i = 0; i < vp.length; i++) {
                    // Picture dimensions are numerical integer
                    let ph = pic[i].naturalHeight;
                    let pw = pic[i].naturalWidth;

                    // Viewport dimensions are strings with an integer ended by "px"
                    let vh = window.getComputedStyle(vp[i], null)
                                .getPropertyValue("height").toString();
                    let vw = window.getComputedStyle(vp[i], null)
                                .getPropertyValue("width").toString();
        
                    if (ph > pw) {
                        pic[i].style.width = vw;
                        let x = `${(parseInt(vh) - ((parseInt(vw) * ph) / pw)) / 2}px`;
                        pic[i].style.top = x;
                    } else {
                        pic[i].style.height = vh;
                        let x = `${(parseInt(vw) - ((parseInt(vh) * pw) / ph)) / 2}px`;
                        pic[i].style.left = x;
                    }
                }
            });
        </script>
    </body>
</html>